from PyQt5 import QtCore, QtGui, QtWidgets
from cls import Human, creator_df
import pandas as pd

table = creator_df()

table1 = pd.read_csv('driver.csv', names=['Модель автомобиля', 'Номер', 'Штраф'], skiprows=[0])
table2 = pd.read_csv('cars.csv', names=['Имя', 'Фамилия', 'Штраф'], skiprows=[0])


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(791, 561)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 751, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(340, 190, 256, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(60, 70, 181, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(350, 160, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(60, 50, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 71, 16))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(50, 190, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(80, 110, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 40, 131, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(330, 40, 111, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 40, 131, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 90, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(180, 20, 51, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(330, 20, 121, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(590, 40, 111, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(590, 20, 121, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(460, 40, 111, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(460, 20, 121, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 90, 141, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 151, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 60, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 70, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 70, 113, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(40, 50, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(190, 50, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(40, 120, 151, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(40, 170, 113, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(190, 170, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(40, 150, 121, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(190, 150, 121, 16))
        self.label_14.setObjectName("label_14")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 160, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(480, 20, 191, 121))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_2.setGeometry(QtCore.QRect(480, 160, 191, 121))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.tab_3, "")

        self.add_function()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Штраф"))
        self.label.setText(_translate("Dialog", "Номер статьи"))
        self.label_2.setText(_translate("Dialog", "Содержание"))
        self.pushButton.setText(_translate("Dialog", "Поиск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Обзор статьи"))
        self.pushButton_2.setText(_translate("Dialog", "Добавить водителя"))
        self.label_4.setText(_translate("Dialog", "Имя"))
        self.label_5.setText(_translate("Dialog", "Фамилия"))
        self.label_6.setText(_translate("Dialog", "Модель автомобиля"))
        self.label_7.setText(_translate("Dialog", "Номер штрафа"))
        self.label_8.setText(_translate("Dialog", "Номер автомобиля"))
        self.pushButton_3.setText(_translate("Dialog", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Учёт"))
        self.label_9.setText(_translate("Dialog", "Поиск по водителю"))
        self.pushButton_5.setText(_translate("Dialog", "Поиск"))
        self.label_10.setText(_translate("Dialog", "Имя"))
        self.label_11.setText(_translate("Dialog", "Фамилия"))
        self.label_12.setText(_translate("Dialog", "Поиск по автомобилю"))
        self.label_13.setText(_translate("Dialog", "Модель автомобиля"))
        self.label_14.setText(_translate("Dialog", "Номер автомобиля"))
        self.pushButton_6.setText(_translate("Dialog", "Поиск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Поиск штрафов"))

    def add_function(self):
        self.pushButton.clicked.connect(lambda: self.searcher(self.lineEdit.text()))
        self.pushButton_2.clicked.connect(lambda: self.add_driver(self.lineEdit_2.text(), self.lineEdit_4.text(),
                                                                  self.lineEdit_3.text(), self.lineEdit_6.text(),
                                                                  self.lineEdit_5.text()))
        self.pushButton_5.clicked.connect(lambda: self.searcher_driver(self.lineEdit_7.text(), self.lineEdit_8.text()))
        self.pushButton_6.clicked.connect(lambda: self.searcher_cars(self.lineEdit_9.text(), self.lineEdit_10.text()))
        self.pushButton_3.clicked.connect(lambda: self.saver())

    def searcher(self, number):
        self.textBrowser_2.setText(table.loc[number, 'Санкции/Меры'])
        self.textBrowser.setText(table.loc[number, 'Правонарушение'])

    def add_driver(self, name, s_name, model, num_auto, num_fine):
        human = Human(name, s_name, model, num_auto, num_fine)
        table1.loc[human.name + ' ' + human.second_name] = [human.car, human.number, human.fines]
        table2.loc[human.car + ' ' + human.number] = [human.name, human.second_name, human.fines]

    def searcher_driver(self, name, s_name):
        self.textEdit.setText(str(table1.loc[name + ' ' + s_name]['Модель автомобиля']) +
                              '\n' + str(table1.loc[name + ' ' + s_name]['Номер']) + '\n' +
                              str(table1.loc[name + ' ' + s_name]['Штраф']))

    def searcher_cars(self, model, number):
        self.textEdit_2.setText(str(table2.loc[model + ' ' + number]['Имя']) +
                                '\n' + str(table2.loc[model + ' ' + number]['Фамилия']) + '\n' +
                                str(table2.loc[model + ' ' + number]['Штраф']))

    def saver(self):
        table1.to_csv('driver.csv')
